### ISSUE TITLE
Website RoadMap

### ISSUE THREAD

**Issue by amitkumarj441** [quanonblocks/quanonblocks.github.io#3]
Tabs to be added:
 - [x] Teams
 - [x] Contact ( Either email or a feedback form)
 - [x] Add Live Chat corner like Twilio etc.
 - [ ] Any other idea?? 
 
Analytics for our website.
P.S. : Send me the website domain access, I'll get you done this work asap :robot: 

@akshayaurora Let's get everything going here related to website contents!

**Comment by rajataaron** [comment]
Contact Form not run on gh-pages

**Comment by amitkumarj441** [comment]
Thanks @rajataaron . 
I just updated the Roadmap :information_source:

**Comment by akshayaurora** [comment]
@amitkumarj441 this can be closed ?

**Comment by amitkumarj441** [comment]
@akshayaurora No, don't close this issue.
Roadmap is forever, you can add  the upcoming tasks as we go ahead.

**Comment by akshayaurora** [comment]
@amitkumarj441 ok, then let us put them in a list,  with items that can be ticked

- [x] Done
- [ ] ToDo

**Comment by amitkumarj441** [comment]
Thanks @akshayaurora for the idea :octocat:
